version: 2
jobs:
  build:
    working_directory: ~/aep-api
    docker:
      - image: circleci/node:8.10
      - image: circleci/mongo:4.1.9

    steps:
      - checkout:
          path: ~/aep-api

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn build

      # run tests!
      - run: yarn test

      - store_artifacts:
          path: test/results.xml
          prefix: TestResults

      - store_test_results:
          path: test
workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: TESTING
          filters:
            branches:
              only:
                - master
                - projects/api-creation
